### PR TITLE
Update qbcore.yaml

### PR DESCRIPTION
**Pull request by cammygames**

### CODE REVIEW

**Comment by ChatDisabled** [comment]
Saw this too, same goes for ox_target so currently looking into it

**Comment by cammygames** [comment]
ox_target doesnt seem to publish a ox_target.zip with the release. Also appears that the zips they publish have the folder in side of them so unpacks as ox_lib/ox_lib/.

**Comment by ChatDisabled** [comment]
@trclassic92 fault for adding the extra folder in the structure :D

**Comment by cammygames** [comment]
😆

**Comment by cammygames** [comment]
Until ox_target publishes a ox_target.zip as part of the release. Maybe swap it over to the current tag src zip and add a step to move path to fix the fact the folder it will extract to will be something like ox_target-1.1.3?

**Comment by ChatDisabled** [comment]
Waiting on https://github.com/overextended/ox_target/issues/11 before I update this further

**Comment by trclassic92** [comment]
Implemented in commit b2f37e27b8e26b4a2c0e32cd5676507ca1152cd4

> Waiting on [overextended/ox_target#11](https://github.com/overextended/ox_target/issues/11) before I update this further

**Pull request merged**
